name: Feature Request
description: Suggest a new idea or request a missing feature

body:
  - type: markdown
    attributes:
      value:
          * Be sure to search open and closed issues for duplicates

  - type: textarea
    attributes:
      label: Problem
      description: Describe the problem that this new feature or idea is meant to address
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposal
      description: Describe the new feature or idea that you would like to propose and how it solves the problem
    validations:
      required: true

  - type: textarea
    attributes:
      label: Prior Implementations (Optional)
      description: List any supporting examples of how others have implemented this feature
    validations:
      required: false
